layout_spectrum: 0.06974999117664993
typography_spectrum: 0.9634539873804897
color:
  brandColors:
    - '#F6F792'
    - '#333745'
    - '#77C4D3'
    - '#DAEDE2'
    - '#EA2E49'
  brandStrength: 0.9116081844549626
  lightness: 0.5182628524489701
  saturation: 0.28948994679376483
  rhythmicContrast: 0.642711628228426
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Zack
  email: zack@zackowen.com
  url: www.zackowen.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dbb0fc95-0bad-42bf-a57c-c115642c0271.png
name: zackowen
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0910e7d5-1f2f-4fd3-95ce-7209782af97f.ico
title: ''
description: ''
purpose: []
