typography_spectrum: 0.15708
color:
  brandColors:
    - '#024959'
    - '#037e8c'
    - '#f2efdc'
    - '#404040'
    - '#f24c27'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: zackowen
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Graphic Designer & Photographer
purpose: []
