layout_spectrum: 0.06974999117664993
typography_spectrum: 0.7181604551151395
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.5629197282250971
  lightness: 0.5007157903164625
  saturation: 0.8102011070586741
  rhythmicContrast: 0.9702424977440387
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: zackowen
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: zackowen
description: Graphic Designer & Photographer
purpose: []
