name: zackowen
favicon: null
layout_spectrum: 0.11549
typography_spectrum: 0.15708
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#030301'
    - '#6e92d3'
    - '#1a436d'
    - '#e96925'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
