typography_spectrum: 0.7181604551151395
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.5629197282250971
  lightness: 0.5007157903164625
  saturation: 0.8102011070586741
  rhythmicContrast: 0.9702424977440387
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.06974999117664993
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Zack
  email: zack@zackowen.com
  url: www.zackowen.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dbb0fc95-0bad-42bf-a57c-c115642c0271.png
name: zackowen
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0910e7d5-1f2f-4fd3-95ce-7209782af97f.ico
title: zackowen
description: Graphic Designer & Photographer
purpose: []
